# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160607_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
    ]
