# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.StatusType'),
        ),
    ]
