# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='remarks',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
