# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 01:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidate_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='min_salary',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.9), django.core.validators.MaxValueValidator(58)]),
        ),
    ]
