# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160609_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='remarks',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
