# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160613_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
