# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160613_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
